vadim_task_creator:
        resource: "@VadimTaskBundle/Resources/config/routing/creator.yml"
        prefix:   /creator

vadim_task_category:
        resource: "@VadimTaskBundle/Resources/config/routing/category.yml"
        prefix:   /category

vadim_task_project:
        resource: "@VadimTaskBundle/Resources/config/routing/project.yml"
        prefix:   /project
